### ISSUE TITLE
widths is ignored when dynfilters is used

### ISSUE THREAD

**Issue by radicarl** [splitbrain/dokuwiki-plugin-data#205]
With the bootstrap-theme widths indications are ignored if dynsfilters is used at the same time.

```
---- datatable ----
headers : Change-Titel, Change Nr, Datum, Uhrzeit, Stage, Wer,  Releases
cols    : %title%, Change Nr., Start Datum, Start Uhrzeit, Stage, Provider,  Releases_schnittstellenreleases
filter  : %class% = eai_change
and     : %pageide% !~ *template*
and     : Start Datum >= %now%
sort    : ^Start Datum
widths  : -, 90px, 70px, 60px, 80px, 55px, 250px
dynfilters: 1
----
```

![screenshot003](https://cloud.githubusercontent.com/assets/1108495/19716841/2225f09a-9b5e-11e6-9eb8-43d8864b6847.png)

without dynfilsters:
![screenshot004](https://cloud.githubusercontent.com/assets/1108495/19716909/65dc8f9c-9b5e-11e6-9a26-67e2318794b9.png)

I made the following changes to the style.css:

``` css
table.dataplugin_table th input {
    width: 98% !important;
}

table.dataplugin_table .control-label {
    display: block !important;
}
```

and the result looks fine:
![screenshot005](https://cloud.githubusercontent.com/assets/1108495/19716987/d68b0048-9b5e-11e6-8fcd-551b45eb18d8.png)
